tps-tresholds:
  tick:
    EntityChicken: 10
    EntityPig: 10
    EntityArmorStand: 10
    EntityCow: 10
    EntityPlayer: 10
    EntityLightning: 10
    EntityItem: 10
    EntitySpider: 10
    EntitySkeleton: 10
    EntityCreeper: 10
    EntityZombie: 10
    EntitySheep: 10
    EntityVillager: 10
    EntityCat: 10
    EntitySlime: 10
    EntityIronGolem: 10
    EntityWolf: 10
    EntityZombieVillager: 10
    EntityFireworks: 10
    EntityPigZombie: 10
    EntityExperienceOrb: 10
    EntityTNTPrimed: 10
    EntityWitch: 10
    EntityPainting: 10
    EntityMinecartHopper: 10
    EntityItemFrame: 10
    EntityZombieHusk: 10
    EntityHorseSkeleton: 10
    GlowItemFrame: 10
    EntityHorse: 10
    EntitySnowman: 10
    EntitySkeletonWither: 10
    EntityBat: 10
    GlowSquid: 10
    EntitySmallFireball: 10
    EntityLargeFireball: 10
    EntityFishingHook: 10
    EntityEnderman: 10
    EntityVillagerTrader: 10
    EntityLlamaTrader: 10
    EntityBoat: 10
    EntityPanda: 10
    EntityHorseDonkey: 10
    EntityMinecartRideable: 10
    EntityPhantom: 10
    EntityBee: 10
    EntityEndermite: 10
    EntityTippedArrow: 10
    EntityEgg: 10
    EntityPiglin: 10
    EntityGhast: 10
    EntityBlaze: 10
    EntityMagmaCube: 10
    EntityWitherSkull: 10
    EntityOcelot: 10
    EntityTurtle: 10
    EntityStrider: 10
    EntityCaveSpider: 10
    EntityDolphin: 10
    EntitySnowball: 10
    EntitySkeletonStray: 10
    EntityRabbit: 10
    EntityFallingBlock: 10
    EntityThrownExpBottle: 10
    EntityPotion: 10
    EntityLlamaSpit: 10
    EntityFox: 10
    EntityLeash: 10
    EntityPolarBear: 10
    EntityDrowned: 10
    EntityThrownTrident: 10
    EntitySquid: 10
    EntityCod: 10
    EntityTropicalFish: 10
    EntitySalmon: 10
    EntityPillager: 10
    EntityEnderPearl: 10
    EntityParrot: 10
    EntityEnderCrystal: 10
    EntityPufferFish: 10
    EntitySpectralArrow: 10
    EntityAreaEffectCloud: 10
    EntityWither: 10
    EntityEvoker: 10
    EntityVex: 10
    EntitySilverfish: 10
    EntityMinecartChest: 10
    EntityEvokerFangs: 10
    EntityVindicator: 10
    EntityRavager: 10
    EntityDragonFireball: 10
    EntityHorseZombie: 10
    EntityEnderSignal: 10
    Axolotl: 10
    EntityGuardianElder: 10
    EntityLlama: 10
    Goat: 10
    EntityShulker: 10
    Frog: 10
    EntityGuardian: 10
    Warden: 10
